# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "win2012_r2_x64"
  config.vm.communicator = :winrm
  config.vm.guest = :windows
  config.vm.boot_timeout = 30
  config.vm.network "forwarded_port", host: 33389, guest: 3389
  config.vm.provider "virtualbox" do |v|
    v.gui = true
  end

end
